version: '3.8'

services:
  api:
    build:
      context: ./backend/AlmadenApi  # Caminho correto para o diretório onde o Dockerfile está
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:80:8080"
    networks:
      - sql_network
    depends_on:
      - sqlserver
    environment:
      - DATABASE_HOST=sqlserver
      - DATABASE_PORT=1433
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=YourStrong!Passw0rd
      - DATABASE_NAME=AlmadenDB
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=AlmadenDB;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True; 
    command: ["./wait-for-it.sh", "sqlserver:1433", "--", "dotnet", "AlmadenApi.dll"]

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - sql_network

volumes:
  sql_data:
    driver: local

networks:
  sql_network:
    driver: bridge
